import { db, categoriesTable, productsTable } from "@workspace/db";
import { sql } from "drizzle-orm";
import type { Logger } from "pino";

const categories = [
  { id: 1, name: "Pharmaceuticals", slug: "pharmaceuticals", description: "Essential medicines and prescription drugs for various health conditions", imageUrl: null },
  { id: 2, name: "Medical Devices", slug: "medical-devices", description: "Diagnostic and therapeutic medical equipment for professional and home use", imageUrl: null },
  { id: 3, name: "Surgical Supplies", slug: "surgical-supplies", description: "Sterile surgical instruments, wound care, and operating room supplies", imageUrl: null },
  { id: 4, name: "Personal Protective Equipment", slug: "ppe", description: "Gloves, masks, gowns and other protective equipment for healthcare settings", imageUrl: null },
  { id: 5, name: "Diagnostics & Lab", slug: "diagnostics-lab", description: "Laboratory test kits, reagents, and diagnostic equipment", imageUrl: null },
  { id: 6, name: "Health & Wellness", slug: "health-wellness", description: "Vitamins, supplements, and general wellness products", imageUrl: null },
  { id: 7, name: "First Aid", slug: "first-aid", description: "First aid kits, bandages, antiseptics, and emergency care supplies", imageUrl: null },
  { id: 8, name: "Maternal & Child Health", slug: "maternal-child-health", description: "Products for mother and child care, infant health supplies", imageUrl: null },
  { id: 9, name: "General Medicine", slug: "general-medicine", description: "Essential diagnostic and examination tools for general medical practice", imageUrl: null },
  { id: 10, name: "Surgery", slug: "surgery", description: "Operating room equipment, sterilization, and surgical supplies", imageUrl: null },
  { id: 11, name: "Pediatrics", slug: "pediatrics", description: "Specialized equipment for neonatal and pediatric care", imageUrl: null },
  { id: 12, name: "Gynecology & Obstetrics", slug: "gynecology-obstetrics", description: "Equipment for womens health, prenatal care, and delivery", imageUrl: null },
  { id: 13, name: "ENT", slug: "ent", description: "Ear, nose and throat diagnostic and therapeutic equipment", imageUrl: null },
  { id: 14, name: "Dentistry", slug: "dentistry", description: "Dental chairs, instruments, and oral care equipment", imageUrl: null },
  { id: 15, name: "Physiotherapy & Rehabilitation", slug: "physiotherapy", description: "Exercise and rehabilitation equipment for physical therapy", imageUrl: null },
  { id: 16, name: "Laboratory", slug: "laboratory", description: "Lab analyzers, microscopes, centrifuges, and diagnostic equipment", imageUrl: null },
  { id: 17, name: "Radiology & Imaging", slug: "radiology-imaging", description: "X-ray machines, ultrasound scanners, and imaging equipment", imageUrl: null },
  { id: 18, name: "Cardiology", slug: "cardiology", description: "ECG machines, defibrillators, and cardiac monitoring equipment", imageUrl: null },
  { id: 19, name: "Ophthalmology", slug: "ophthalmology", description: "Eye examination and treatment equipment", imageUrl: null },
  { id: 20, name: "Respiratory Care", slug: "respiratory-care", description: "Ventilators, nebulizers, oxygen therapy, and respiratory equipment", imageUrl: null },
  { id: 21, name: "Patient Monitoring", slug: "patient-monitoring", description: "Vital signs monitors, ICU equipment, and patient tracking systems", imageUrl: null },
  { id: 22, name: "Sterilization & Disinfection", slug: "sterilization", description: "Autoclaves, UV sterilizers, and infection control equipment", imageUrl: null },
  { id: 23, name: "Hospital Furniture", slug: "hospital-furniture", description: "Hospital beds, examination tables, trolleys, and medical furniture", imageUrl: null },
  { id: 24, name: "Emergency & Trauma", slug: "emergency-trauma", description: "Emergency trolleys, defibrillators, and trauma care supplies", imageUrl: null },
];

const products = [
  { id: 1, name: "Amoxicillin 500mg Capsules", description: "Broad-spectrum antibiotic used to treat bacterial infections including respiratory tract infections, urinary tract infections, and skin infections. Pack of 30 capsules.", price: "8.50", originalPrice: "12.00", imageUrl: "/products/product-1.webp", categoryId: 1, inStock: true, stockQuantity: 500, featured: true, prescriptionRequired: true, manufacturer: "PharmaCo Ltd", sku: "AMX-500-30" },
  { id: 2, name: "Paracetamol 1000mg Tablets", description: "Effective pain relief and fever reducer. Suitable for adults and children over 12 years. Pack of 100 tablets. Fast-acting formula for headaches, dental pain, and fever.", price: "5.99", originalPrice: null, imageUrl: "/products/product-2.webp", categoryId: 1, inStock: true, stockQuantity: 1200, featured: true, prescriptionRequired: false, manufacturer: "MediGen", sku: "PAR-1000-100" },
  { id: 3, name: "Omeprazole 20mg Capsules", description: "Proton pump inhibitor for the treatment of acid reflux, gastroesophageal reflux disease (GERD), and stomach ulcers. Pack of 28 capsules.", price: "11.75", originalPrice: "15.00", imageUrl: "/products/product-3.webp", categoryId: 1, inStock: true, stockQuantity: 300, featured: false, prescriptionRequired: true, manufacturer: "GastroPharma", sku: "OMP-20-28" },
  { id: 4, name: "Metformin 850mg Tablets", description: "Oral antidiabetic medication used to treat type 2 diabetes. Helps control blood sugar levels. Pack of 60 tablets. Prescription required.", price: "9.25", originalPrice: null, imageUrl: "/products/product-4.webp", categoryId: 1, inStock: true, stockQuantity: 400, featured: false, prescriptionRequired: true, manufacturer: "DiabetaCare", sku: "MET-850-60" },
  { id: 5, name: "Digital Blood Pressure Monitor", description: "Automatic upper-arm blood pressure monitor with large LCD display. Stores up to 120 readings with date and time. Irregular heartbeat detection feature. Includes carrying case.", price: "45.00", originalPrice: "65.00", imageUrl: "/products/product-5.webp", categoryId: 2, inStock: true, stockQuantity: 80, featured: true, prescriptionRequired: false, manufacturer: "VitalSign Tech", sku: "BP-MON-AUTO" },
  { id: 6, name: "Pulse Oximeter", description: "Fingertip pulse oximeter for accurate SpO2 and pulse rate measurement. OLED display, auto power off, and battery level indicator. Suitable for sports, aviation, and clinical use.", price: "22.50", originalPrice: "35.00", imageUrl: "/products/product-6.webp", categoryId: 2, inStock: true, stockQuantity: 150, featured: true, prescriptionRequired: false, manufacturer: "OxyMed", sku: "OXY-FP-01" },
  { id: 7, name: "Digital Thermometer", description: "Fast and accurate digital thermometer with 10-second reading. Flexible tip for comfort. Memory recall for last reading. Suitable for oral, axillary, and rectal use.", price: "8.99", originalPrice: null, imageUrl: "/products/product-7.webp", categoryId: 2, inStock: true, stockQuantity: 300, featured: false, prescriptionRequired: false, manufacturer: "TempCheck", sku: "THERM-DIG-01" },
  { id: 8, name: "Stethoscope Professional", description: "Dual-head stethoscope for professional clinical use. Acoustic performance optimized for cardiac, pulmonary, and pediatric assessment. Latex-free tubing.", price: "38.00", originalPrice: "55.00", imageUrl: "/products/product-8.webp", categoryId: 2, inStock: true, stockQuantity: 60, featured: true, prescriptionRequired: false, manufacturer: "CardioListen", sku: "STETH-PRO-01" },
  { id: 9, name: "Surgical Gloves Sterile Box", description: "Sterile latex surgical gloves, powder-free. Box of 50 pairs. Available in sizes 6.5 to 8.5. Pre-formed fingers for superior fit. Double wrapped for sterility.", price: "28.00", originalPrice: null, imageUrl: "/products/product-9.webp", categoryId: 3, inStock: true, stockQuantity: 200, featured: false, prescriptionRequired: false, manufacturer: "SafeHands Medical", sku: "GLV-SURG-50" },
  { id: 10, name: "Wound Dressing Kit", description: "Comprehensive wound dressing kit including sterile gauze pads, adhesive tape, cotton wool, bandages, and antiseptic wipes. Ideal for post-surgical wound care.", price: "15.50", originalPrice: "20.00", imageUrl: "/products/product-10.webp", categoryId: 3, inStock: true, stockQuantity: 180, featured: false, prescriptionRequired: false, manufacturer: "WoundCare Pro", sku: "WND-KIT-COMP" },
  { id: 11, name: "N95 Respirator Masks Box of 20", description: "NIOSH-certified N95 respirator masks offering 95% filtration of airborne particles. Adjustable nose clip for secure fit. Box of 20 masks. Essential for healthcare settings.", price: "32.00", originalPrice: "45.00", imageUrl: "/products/product-11.webp", categoryId: 4, inStock: true, stockQuantity: 500, featured: true, prescriptionRequired: false, manufacturer: "AirShield Medical", sku: "N95-BOX-20" },
  { id: 12, name: "Medical Examination Gloves 100pcs", description: "Nitrile examination gloves, powder-free, latex-free. Box of 100. Excellent chemical resistance and durability. Textured fingertips for improved grip. Available in S, M, L, XL.", price: "12.00", originalPrice: null, imageUrl: "/products/product-12.webp", categoryId: 4, inStock: true, stockQuantity: 800, featured: true, prescriptionRequired: false, manufacturer: "ProGuard", sku: "GLV-NITR-100" },
  { id: 13, name: "Rapid HIV Test Kit", description: "Highly accurate rapid HIV 1/2 test kit with 99.9% sensitivity. Results in 15 minutes. Includes test device, buffer, lancets, and instructions. Approved for professional use.", price: "18.50", originalPrice: null, imageUrl: "/products/product-13.webp", categoryId: 5, inStock: true, stockQuantity: 250, featured: false, prescriptionRequired: false, manufacturer: "DiagnoTech", sku: "HIV-RAPID-01" },
  { id: 14, name: "Blood Glucose Test Strips 50ct", description: "Compatible test strips for blood glucose monitoring. Accurate results in 5 seconds. No coding required. Pack of 50 strips. Works with most major glucometer brands.", price: "14.99", originalPrice: "18.00", imageUrl: "/products/product-14.webp", categoryId: 5, inStock: true, stockQuantity: 400, featured: true, prescriptionRequired: false, manufacturer: "GlucoTest", sku: "BGS-50-CTR" },
  { id: 15, name: "Vitamin C 1000mg Effervescent", description: "High-strength vitamin C with zinc for immune support. Pleasant orange flavour effervescent tablets. Box of 30 tablets. Suitable for adults and children over 12.", price: "6.50", originalPrice: null, imageUrl: "/products/product-15.webp", categoryId: 6, inStock: true, stockQuantity: 600, featured: true, prescriptionRequired: false, manufacturer: "VitaPlus", sku: "VIT-C-1000-EFF" },
  { id: 16, name: "Omega-3 Fish Oil Capsules", description: "High-potency omega-3 fatty acids for heart health, brain function, and joint support. 1000mg per capsule, 90 softgels. Molecularly distilled for purity.", price: "18.99", originalPrice: "25.00", imageUrl: "/products/product-16.webp", categoryId: 6, inStock: true, stockQuantity: 350, featured: true, prescriptionRequired: false, manufacturer: "OceanHealth", sku: "OMG3-1000-90" },
  { id: 17, name: "First Aid Kit Standard", description: "Comprehensive first aid kit for home, office, or travel use. Includes bandages, antiseptic cream, sterile gauze, scissors, tweezers, gloves, and first aid manual. 85-piece kit.", price: "24.99", originalPrice: "35.00", imageUrl: "/products/product-17.webp", categoryId: 7, inStock: true, stockQuantity: 200, featured: true, prescriptionRequired: false, manufacturer: "SafetyFirst", sku: "FAK-STD-85" },
  { id: 18, name: "Adhesive Bandages Assorted 100ct", description: "Assorted sizes adhesive bandages with antibacterial pad. Hypoallergenic adhesive, comfortable fabric material. Box of 100. Ideal for cuts, blisters, and minor wounds.", price: "7.50", originalPrice: null, imageUrl: "/products/product-18.webp", categoryId: 7, inStock: true, stockQuantity: 700, featured: false, prescriptionRequired: false, manufacturer: "CoverCare", sku: "BND-ASST-100" },
  { id: 19, name: "Stethoscope Classic", description: "Dual-head acoustic stethoscope for general auscultation of heart and lung sounds. Stainless steel chestpiece, flexible tubing, comfortable binaural. Suitable for all clinical settings.", price: "35.00", originalPrice: null, imageUrl: "/products/product-19.webp", categoryId: 9, inStock: true, stockQuantity: 120, featured: true, prescriptionRequired: false, manufacturer: "CardioListen", sku: "STETH-CLASSIC-01" },
  { id: 20, name: "Sphygmomanometer Manual", description: "Aneroid blood pressure monitor with cuff and bulb for manual measurement. Calibrated gauge with carrying case. Latex-free cuff available in standard adult size.", price: "28.50", originalPrice: "38.00", imageUrl: "/products/product-20.webp", categoryId: 9, inStock: true, stockQuantity: 90, featured: false, prescriptionRequired: false, manufacturer: "VitalSign Tech", sku: "SPHYG-MAN-01" },
  { id: 21, name: "Electronic Blood Pressure Monitor", description: "Fully automatic electronic blood pressure monitor with large LCD display. Upper arm cuff, irregular heartbeat detection, 120-reading memory. Includes AC adapter.", price: "55.00", originalPrice: "75.00", imageUrl: "/products/product-21.webp", categoryId: 9, inStock: true, stockQuantity: 75, featured: true, prescriptionRequired: false, manufacturer: "VitalSign Tech", sku: "SPHYG-ELEC-01" },
  { id: 22, name: "Infrared Thermometer", description: "Non-contact infrared thermometer for forehead measurement. Instant 1-second reading with fever alarm. Backlit display, stores 32 readings. Suitable for all ages.", price: "19.99", originalPrice: "28.00", imageUrl: "/products/product-22.webp", categoryId: 9, inStock: true, stockQuantity: 200, featured: false, prescriptionRequired: false, manufacturer: "TempCheck", sku: "THERM-IR-01" },
  { id: 23, name: "Otoscope Diagnostic", description: "Fibre-optic otoscope for examination of the ear canal and eardrum. Rechargeable battery handle, includes 5 specula sizes. Bright halogen light, clear optics.", price: "42.00", originalPrice: null, imageUrl: "/products/product-23.webp", categoryId: 9, inStock: true, stockQuantity: 60, featured: false, prescriptionRequired: false, manufacturer: "DiagnoScope", sku: "OTO-SCOPE-01" },
  { id: 24, name: "Height & Weight Scale (Stadiometer)", description: "Medical scale with integrated height rod (stadiometer). Capacity up to 200kg, 0.1kg accuracy. Height measurement up to 200cm. Suitable for adults.", price: "120.00", originalPrice: "160.00", imageUrl: "/products/product-24.webp", categoryId: 9, inStock: true, stockQuantity: 30, featured: false, prescriptionRequired: false, manufacturer: "MedWeight Pro", sku: "SCALE-STAD-01" },
  { id: 25, name: "Glucometer Blood Glucose Monitor", description: "Portable blood glucose monitoring system. Results in 5 seconds. Includes 10 test strips, 10 lancets, lancing device, and carrying case. No coding required.", price: "32.00", originalPrice: "45.00", imageUrl: "/products/product-25.webp", categoryId: 9, inStock: true, stockQuantity: 150, featured: true, prescriptionRequired: false, manufacturer: "GlucoTest", sku: "GLUCO-MON-01" },
  { id: 26, name: "Examination Lamp (LED)", description: "Flexible gooseneck LED examination lamp on wheeled base. Adjustable brightness, daylight colour temperature. Energy efficient, cool to touch.", price: "85.00", originalPrice: null, imageUrl: "/products/product-26.webp", categoryId: 9, inStock: true, stockQuantity: 40, featured: false, prescriptionRequired: false, manufacturer: "MedLight", sku: "EXAM-LAMP-01" },
  { id: 27, name: "Medical Examination Table", description: "Padded examination table with adjustable backrest. Weight capacity 180kg. Stainless steel frame, easy-clean vinyl upholstery. Paper roll holder included.", price: "350.00", originalPrice: "450.00", imageUrl: "/products/product-27.webp", categoryId: 9, inStock: true, stockQuantity: 15, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "EXAM-TABLE-01" },
  { id: 28, name: "Dressing & Wound Care Set", description: "Complete dressing materials kit: sterile compresses, medical tape (5 rolls), scissors, tweezers, and wound closure strips. Ideal for examination rooms.", price: "22.00", originalPrice: null, imageUrl: "/products/product-28.webp", categoryId: 9, inStock: true, stockQuantity: 200, featured: false, prescriptionRequired: false, manufacturer: "WoundCare Pro", sku: "DRESS-SET-01" },
  { id: 29, name: "Surgical Operating Table", description: "Hydraulic operating table with 4-section top. Electric height adjustment 620-960mm, Trendelenburg +/-30deg, lateral tilt 20deg. Weight capacity 250kg.", price: "2800.00", originalPrice: "3500.00", imageUrl: "/products/product-29.webp", categoryId: 10, inStock: true, stockQuantity: 5, featured: false, prescriptionRequired: false, manufacturer: "SurgTech Pro", sku: "OR-TABLE-01" },
  { id: 30, name: "LED Surgical Shadowless Light", description: "Ceiling-mounted LED surgical shadowless light. 160,000 lux intensity, colour rendering Ra>95. Adjustable arm with 360 degree rotation. Energy efficient and heat-free.", price: "1850.00", originalPrice: "2400.00", imageUrl: "/products/product-30.webp", categoryId: 10, inStock: true, stockQuantity: 8, featured: false, prescriptionRequired: false, manufacturer: "SurgLight", sku: "SURG-LIGHT-01" },
  { id: 31, name: "Multiparameter Patient Monitor", description: "Bedside multiparameter monitor. Displays ECG, SpO2, NIBP, temperature, respiration rate. 12.1 inch colour touchscreen, alarm system, data storage.", price: "1200.00", originalPrice: "1600.00", imageUrl: "/products/product-31.webp", categoryId: 10, inStock: true, stockQuantity: 20, featured: true, prescriptionRequired: false, manufacturer: "VitalMonitor", sku: "MULTI-MON-01" },
  { id: 32, name: "Surgical Suction Machine", description: "Electric surgical aspirator for use in operating rooms and clinics. 700mmHg vacuum, 30L/min flow rate, 2L collection jar. Foot pedal control included.", price: "380.00", originalPrice: "500.00", imageUrl: "/products/product-32.webp", categoryId: 10, inStock: true, stockQuantity: 25, featured: false, prescriptionRequired: false, manufacturer: "SurgAsp", sku: "SUCTION-01" },
  { id: 33, name: "Sterile Surgical Instrument Kit", description: "Complete sterile surgical instrument set including scissors, forceps, retractors, needle holders, and clamps. Stainless steel, autoclavable. Case of 25 instruments.", price: "185.00", originalPrice: "240.00", imageUrl: "/products/product-33.webp", categoryId: 10, inStock: true, stockQuantity: 40, featured: false, prescriptionRequired: false, manufacturer: "SurgInstruments", sku: "SURG-KIT-25" },
  { id: 34, name: "Electrosurgical / Coagulation Unit", description: "Bipolar and monopolar electrosurgical unit for cutting and coagulation. 300W output, programmable settings, safety alarm. Footswitch and handpiece included.", price: "950.00", originalPrice: "1300.00", imageUrl: "/products/product-34.webp", categoryId: 10, inStock: true, stockQuantity: 10, featured: false, prescriptionRequired: false, manufacturer: "ElectroCare", sku: "ESU-300-01" },
  { id: 35, name: "Suture Material Assorted Pack", description: "Assorted sterile suture pack including absorbable (Vicryl) and non-absorbable (Nylon, Prolene) sutures. Various gauges 2-0 to 5-0 with curved needles. Box of 36.", price: "48.00", originalPrice: null, imageUrl: "/products/product-35.webp", categoryId: 10, inStock: true, stockQuantity: 100, featured: false, prescriptionRequired: false, manufacturer: "SuturePro", sku: "SUTURE-ASST-36" },
  { id: 36, name: "Autoclave Steam Sterilizer 23L", description: "Class B steam autoclave sterilizer. 23-litre capacity, fully automatic cycle, digital display. Suitable for wrapped and unwrapped instruments. Safety valve, door lock.", price: "1100.00", originalPrice: "1400.00", imageUrl: "/products/product-36.webp", categoryId: 10, inStock: true, stockQuantity: 12, featured: true, prescriptionRequired: false, manufacturer: "SterilTech", sku: "AUTO-23L-01" },
  { id: 37, name: "Medical Ventilator (ICU)", description: "Advanced ICU ventilator with volume, pressure, and SIMV modes. 7 inch colour display, built-in turbine, integrated humidifier port. Battery backup 4 hours.", price: "4500.00", originalPrice: "5800.00", imageUrl: "/products/product-37.webp", categoryId: 10, inStock: true, stockQuantity: 6, featured: true, prescriptionRequired: true, manufacturer: "VentilPro", sku: "VENT-ICU-01" },
  { id: 38, name: "Emergency Crash Cart Trolley", description: "Fully stocked emergency crash cart with defibrillator shelf. 5 lockable drawers, oxygen cylinder holder, IV pole. Includes ACLS medications tray (empty).", price: "420.00", originalPrice: "580.00", imageUrl: "/products/product-38.webp", categoryId: 10, inStock: true, stockQuantity: 10, featured: false, prescriptionRequired: false, manufacturer: "EmergencyMed", sku: "CRASH-CART-01" },
  { id: 39, name: "Baby & Infant Scale", description: "Digital baby scale with removable tray. Capacity 20kg, accuracy 10g. Tare function, hold function to capture weight of restless infants. Battery powered.", price: "65.00", originalPrice: "90.00", imageUrl: "/products/product-39.webp", categoryId: 11, inStock: true, stockQuantity: 40, featured: false, prescriptionRequired: false, manufacturer: "BabyMed", sku: "BABY-SCALE-01" },
  { id: 40, name: "Pediatric Digital Thermometer", description: "Flexible tip pediatric thermometer for oral, axillary, or rectal use. Fast 10-second reading, fever alarm, waterproof, memory recall. Baby-safe design.", price: "9.99", originalPrice: null, imageUrl: "/products/product-40.webp", categoryId: 11, inStock: true, stockQuantity: 200, featured: false, prescriptionRequired: false, manufacturer: "TempCheck", sku: "THERM-PED-01" },
  { id: 41, name: "Pediatric Stethoscope", description: "Lightweight pediatric stethoscope with small 28mm chestpiece. Excellent acoustic sensitivity for neonatal and infant auscultation. Comfortable soft earpieces.", price: "28.00", originalPrice: "38.00", imageUrl: "/products/product-41.webp", categoryId: 11, inStock: true, stockQuantity: 80, featured: false, prescriptionRequired: false, manufacturer: "CardioListen", sku: "STETH-PED-01" },
  { id: 42, name: "Mesh Nebulizer for Children", description: "Silent vibrating mesh nebulizer for medication delivery to airways. Fits all standard nebulizer cups. Includes pediatric mask, adult mask, and mouthpiece. Battery + USB powered.", price: "45.00", originalPrice: "62.00", imageUrl: "/products/product-42.webp", categoryId: 11, inStock: true, stockQuantity: 90, featured: false, prescriptionRequired: false, manufacturer: "RespiCare", sku: "NEB-MESH-01" },
  { id: 43, name: "Pediatric Stadiometer", description: "Portable pediatric height measurement board (stadiometer). Measures from 10 to 110cm. Wall-mounted or portable use. Easy-read scale, lightweight.", price: "38.00", originalPrice: null, imageUrl: "/products/product-43.webp", categoryId: 11, inStock: true, stockQuantity: 35, featured: false, prescriptionRequired: false, manufacturer: "MedWeight Pro", sku: "STAD-PED-01" },
  { id: 44, name: "Pediatric Pulse Oximeter", description: "Neonatal and pediatric wraparound pulse oximeter probe. Compatible with most patient monitors. Soft, flexible sensor minimizes discomfort. Reusable, autoclavable.", price: "15.00", originalPrice: "22.00", imageUrl: "/products/product-44.webp", categoryId: 11, inStock: true, stockQuantity: 120, featured: false, prescriptionRequired: false, manufacturer: "OxyMed", sku: "OXY-PED-01" },
  { id: 45, name: "Vaccination Tray & Syringe Set", description: "Stainless steel vaccination tray with compartments for syringes and needles. Includes 50 auto-disable syringes (0.5ml and 1ml). Ideal for immunization campaigns.", price: "35.00", originalPrice: null, imageUrl: "/products/product-45.webp", categoryId: 11, inStock: true, stockQuantity: 60, featured: false, prescriptionRequired: false, manufacturer: "VaccinePro", sku: "VAC-TRAY-01" },
  { id: 46, name: "Pediatric Examination Table", description: "Padded pediatric examination table with safety rails and paper roll holder. Colourful, child-friendly design. Height 75cm, load capacity 80kg. Easy-clean surface.", price: "280.00", originalPrice: "360.00", imageUrl: "/products/product-46.webp", categoryId: 11, inStock: true, stockQuantity: 10, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "EXAM-PED-TABLE" },
  { id: 47, name: "Vaginal Speculum Set (Cusco)", description: "Stainless steel Cusco vaginal speculum set. Sizes S, M, L. Autoclavable, polished finish. For routine gynecological examination and procedures.", price: "24.00", originalPrice: null, imageUrl: "/products/product-47.webp", categoryId: 12, inStock: true, stockQuantity: 80, featured: false, prescriptionRequired: false, manufacturer: "GynecoPro", sku: "SPEC-VAG-SET" },
  { id: 48, name: "Transvaginal Ultrasound Probe", description: "High-frequency transvaginal ultrasound probe for detailed pelvic and uterine imaging. 5-9MHz frequency. Compatible with major ultrasound systems. Autoclavable tip cover included.", price: "650.00", originalPrice: "850.00", imageUrl: "/products/product-48.webp", categoryId: 12, inStock: true, stockQuantity: 10, featured: false, prescriptionRequired: false, manufacturer: "UltraView", sku: "PROBE-TVS-01" },
  { id: 49, name: "Gynecological Examination Table", description: "Electric gynecological examination table with leg supports and adjustable backrest. 3-section top, foot control, paper roll holder. Weight capacity 200kg.", price: "1200.00", originalPrice: "1600.00", imageUrl: "/products/product-49.webp", categoryId: 12, inStock: true, stockQuantity: 8, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "GYN-TABLE-01" },
  { id: 50, name: "Fetal Doppler Monitor", description: "Handheld fetal doppler for monitoring fetal heart rate from week 12 onwards. Waterproof probe, LCD display showing FHR and pulse rate. Includes ultrasound gel.", price: "55.00", originalPrice: "75.00", imageUrl: "/products/product-50.webp", categoryId: 12, inStock: true, stockQuantity: 50, featured: true, prescriptionRequired: false, manufacturer: "FetoCare", sku: "DOPPLER-FET-01" },
  { id: 51, name: "Delivery & Obstetric Kit", description: "Sterile delivery kit for normal vaginal delivery. Includes cord clamps, scissors, gauze, drapes, gloves, and umbilical clamp. Single-use sterile pack.", price: "18.50", originalPrice: null, imageUrl: "/products/product-51.webp", categoryId: 12, inStock: true, stockQuantity: 100, featured: false, prescriptionRequired: false, manufacturer: "OBGyn Supply", sku: "DELIVERY-KIT-01" },
  { id: 52, name: "Obstetrical Ultrasound Machine", description: "Portable color doppler ultrasound machine for obstetrics and gynecology. 15 inch LED monitor, 3 probe ports, OB/GYN measurement packages. Internal storage, DICOM compatible.", price: "5500.00", originalPrice: "7200.00", imageUrl: "/products/product-52.webp", categoryId: 12, inStock: true, stockQuantity: 4, featured: true, prescriptionRequired: false, manufacturer: "UltraView", sku: "US-OBS-PORT-01" },
  { id: 53, name: "Diagnostic Otoscope & Ophthalmoscope Set", description: "Combined otoscope and ophthalmoscope diagnostic set. Fibre-optic light, rechargeable handle. 8 specula sizes, matching ophthalmoscope head. Professional carry case.", price: "95.00", originalPrice: "130.00", imageUrl: "/products/product-53.webp", categoryId: 13, inStock: true, stockQuantity: 45, featured: false, prescriptionRequired: false, manufacturer: "DiagnoScope", sku: "ENT-DIAG-SET" },
  { id: 54, name: "Nasal Speculum (Killian)", description: "Stainless steel Killian nasal speculum for anterior rhinoscopy. Available in 75mm and 100mm blade lengths. Autoclavable, chrome-plated finish.", price: "18.00", originalPrice: null, imageUrl: "/products/product-54.webp", categoryId: 13, inStock: true, stockQuantity: 60, featured: false, prescriptionRequired: false, manufacturer: "ENT Pro", sku: "SPEC-NASAL-01" },
  { id: 55, name: "Laryngoscope Set (Macintosh)", description: "Standard Macintosh laryngoscope handle with 4 blade sizes (1, 2, 3, 4). Fibre-optic cold light illumination. Stainless steel blades, autoclavable. Carry case included.", price: "65.00", originalPrice: "90.00", imageUrl: "/products/product-55.webp", categoryId: 13, inStock: true, stockQuantity: 30, featured: false, prescriptionRequired: false, manufacturer: "ENT Pro", sku: "LARYNGO-MAC-SET" },
  { id: 56, name: "ENT Headlight LED", description: "LED headlight for ENT examinations. Lightweight aluminium frame, adjustable forehead band. Spot size and intensity adjustment. Battery pack included. 50,000 hour LED life.", price: "120.00", originalPrice: "160.00", imageUrl: "/products/product-56.webp", categoryId: 13, inStock: true, stockQuantity: 25, featured: false, prescriptionRequired: false, manufacturer: "MedLight", sku: "ENT-HEADLIGHT-01" },
  { id: 57, name: "Dental Chair Unit", description: "Full dental chair unit with integrated delivery system. Hydraulic chair, LED dental lamp, 3-way syringe, suction motor, spittoon, operating light. All-in-one setup.", price: "3200.00", originalPrice: "4200.00", imageUrl: "/products/product-57.webp", categoryId: 14, inStock: true, stockQuantity: 5, featured: true, prescriptionRequired: false, manufacturer: "DentaCare Systems", sku: "DENTAL-CHAIR-01" },
  { id: 58, name: "Dental X-Ray Machine (Intraoral)", description: "DC intraoral dental X-ray unit. 60kV, 2mA, 0.08s exposure. Wall-mounted arm, digital sensor compatible. CE/FDA approved. Low radiation dose.", price: "1800.00", originalPrice: "2400.00", imageUrl: "/products/product-58.webp", categoryId: 14, inStock: true, stockQuantity: 8, featured: false, prescriptionRequired: false, manufacturer: "DentaRad", sku: "DENTAL-XRAY-01" },
  { id: 59, name: "Dental Autoclave (Class B, 17L)", description: "Class B dental autoclave sterilizer. 17-litre chamber, 134 degree C cycle, vacuum pre and post. Fully automatic, digital display, printer. For wrapped instrument sterilization.", price: "1400.00", originalPrice: "1800.00", imageUrl: "/products/product-59.webp", categoryId: 14, inStock: true, stockQuantity: 10, featured: false, prescriptionRequired: false, manufacturer: "SterilTech", sku: "DENTAL-AUTO-17L" },
  { id: 60, name: "Dental Instrument Kit", description: "Basic dental instrument set: dental mirror, probe/explorer, excavator, sickle scaler, curette, college tweezers, cement spatula. Stainless steel, autoclavable. Set of 8.", price: "45.00", originalPrice: null, imageUrl: "/products/product-60.webp", categoryId: 14, inStock: true, stockQuantity: 80, featured: false, prescriptionRequired: false, manufacturer: "DentaCare Systems", sku: "DENTAL-KIT-8" },
  { id: 61, name: "Physiotherapy Ultrasound Therapy Unit", description: "Therapeutic ultrasound machine for deep tissue healing. 1MHz and 3MHz frequencies, intensity 0-3W/cm2, continuous and pulse modes. Digital timer, treatment head included.", price: "320.00", originalPrice: "420.00", imageUrl: "/products/product-61.webp", categoryId: 15, inStock: true, stockQuantity: 20, featured: false, prescriptionRequired: false, manufacturer: "ElectroTherapy", sku: "PHYSIO-US-01" },
  { id: 62, name: "Infrared Lamp (250W)", description: "Medical infrared therapy lamp. 250W ruby bulb, adjustable height stand, tilting head. Heat therapy for muscle pain, joint stiffness, and wound healing. Protective guard.", price: "55.00", originalPrice: "75.00", imageUrl: "/products/product-62.webp", categoryId: 15, inStock: true, stockQuantity: 40, featured: false, prescriptionRequired: false, manufacturer: "MedLight", sku: "IR-LAMP-250W" },
  { id: 63, name: "Traction Therapy Unit (Cervical/Lumbar)", description: "Motorized intermittent traction unit for cervical and lumbar spine. Load range 1-60kg, digital timer, adjustable cycles. Includes cervical halter and lumbar belt.", price: "380.00", originalPrice: "500.00", imageUrl: "/products/product-63.webp", categoryId: 15, inStock: true, stockQuantity: 8, featured: false, prescriptionRequired: false, manufacturer: "RehabTech", sku: "TRACTION-MOT-01" },
  { id: 64, name: "Hydrotherapy Whirlpool Bath", description: "Stainless steel hydrotherapy whirlpool for extremity rehabilitation. 120-litre tank, adjustable jets and temperature. Foot and hand versions available. Mobile on castors.", price: "1200.00", originalPrice: "1600.00", imageUrl: "/products/product-64.webp", categoryId: 15, inStock: true, stockQuantity: 5, featured: false, prescriptionRequired: false, manufacturer: "RehabTech", sku: "HYDRO-WHIRL-01" },
  { id: 65, name: "Exercise Bike / Pedal Exerciser", description: "Upright exercise bike for cardiac and orthopedic rehabilitation. Adjustable resistance, 7 inch LCD console showing time, speed, distance, calories, heart rate.", price: "480.00", originalPrice: "650.00", imageUrl: "/products/product-65.webp", categoryId: 15, inStock: true, stockQuantity: 15, featured: false, prescriptionRequired: false, manufacturer: "RehabTech", sku: "BIKE-REHAB-01" },
  { id: 66, name: "Physiotherapy Treatment Table", description: "Adjustable height physiotherapy treatment table. Electric lift 55-90cm, 3-section top, padded surface. Weight capacity 200kg. Paper roll holder, sturdy steel frame.", price: "650.00", originalPrice: "850.00", imageUrl: "/products/product-66.webp", categoryId: 15, inStock: true, stockQuantity: 12, featured: false, prescriptionRequired: false, manufacturer: "RehabFurniture", sku: "PHYSIO-TABLE-01" },
  { id: 67, name: "Resistance Therapy Bands Set", description: "Set of 5 latex resistance therapy bands in progressive resistance levels (yellow to black). 1.5m length each. Suitable for strength, flexibility, and rehabilitation exercise.", price: "18.00", originalPrice: null, imageUrl: "/products/product-67.webp", categoryId: 15, inStock: true, stockQuantity: 150, featured: false, prescriptionRequired: false, manufacturer: "FlexiRehab", sku: "BANDS-RESIST-SET" },
  { id: 68, name: "TENS / EMS Electrostimulator", description: "Dual-channel TENS/EMS electrostimulator for pain relief and muscle re-education. 24 preset programs, adjustable intensity, large LCD display. Includes 4 electrode pads.", price: "85.00", originalPrice: "120.00", imageUrl: "/products/product-68.webp", categoryId: 15, inStock: true, stockQuantity: 50, featured: false, prescriptionRequired: false, manufacturer: "ElectroTherapy", sku: "TENS-EMS-01" },
  { id: 69, name: "Parallel Bars Rehabilitation", description: "Height and width adjustable parallel bars for gait training and balance rehabilitation. Steel construction, non-slip rubber feet. Height 65-105cm, length 3m.", price: "520.00", originalPrice: "680.00", imageUrl: "/products/product-69.webp", categoryId: 15, inStock: true, stockQuantity: 6, featured: false, prescriptionRequired: false, manufacturer: "RehabTech", sku: "PARALLEL-BARS-01" },
  { id: 70, name: "Rehabilitation Therapy Balls Set", description: "Set of 4 anti-burst exercise balls for physiotherapy: 45cm, 55cm, 65cm, 75cm. Each includes inflation pump and exercise guide. Supports up to 300kg.", price: "65.00", originalPrice: null, imageUrl: "/products/product-70.webp", categoryId: 15, inStock: true, stockQuantity: 40, featured: false, prescriptionRequired: false, manufacturer: "FlexiRehab", sku: "REHAB-BALLS-SET" },
  { id: 71, name: "Binocular Microscope", description: "Professional binocular laboratory microscope. 40x-1600x magnification, LED illumination, mechanical stage, coarse and fine focus. Includes 4 objectives and carrying case.", price: "380.00", originalPrice: "500.00", imageUrl: "/products/product-71.webp", categoryId: 16, inStock: true, stockQuantity: 25, featured: true, prescriptionRequired: false, manufacturer: "OptoLab", sku: "MICRO-BINO-01" },
  { id: 72, name: "Laboratory Microscope Slides & Cover Slips", description: "Box of 100 pre-cleaned glass microscope slides (75x25mm) and 100 cover slips (22x22mm, 0.13-0.17mm). Frosted end for labeling. Suitable for routine lab work.", price: "14.50", originalPrice: null, imageUrl: "/products/product-72.webp", categoryId: 16, inStock: true, stockQuantity: 300, featured: false, prescriptionRequired: false, manufacturer: "LabSupply", sku: "SLIDES-BOX-100" },
  { id: 73, name: "Centrifuge 24-Place", description: "Benchtop centrifuge. 24-place rotor for 15ml tubes, max 4000 RPM, digital timer, brushless motor. Quiet operation, lid lock safety, imbalance detection.", price: "320.00", originalPrice: "420.00", imageUrl: "/products/product-73.webp", categoryId: 16, inStock: true, stockQuantity: 18, featured: false, prescriptionRequired: false, manufacturer: "LabCentro", sku: "CENTRI-24-01" },
  { id: 74, name: "Blood Collection Tube Set", description: "Vacuum blood collection tube assortment: EDTA (purple), SST (gold), citrate (blue), plain (red). Box of 100 each size. Compatible with standard vacutainer systems.", price: "28.00", originalPrice: null, imageUrl: "/products/product-74.webp", categoryId: 16, inStock: true, stockQuantity: 200, featured: false, prescriptionRequired: false, manufacturer: "LabSupply", sku: "TUBES-SET-400" },
  { id: 75, name: "Automatic Pipette Set (Micropipette)", description: "Set of 3 single-channel adjustable micropipettes: 0.5-10μl, 20-200μl, 100-1000μl. Autoclavable, lightweight, ergonomic design. Includes stand and 1000 tips.", price: "185.00", originalPrice: "250.00", imageUrl: "/products/product-75.webp", categoryId: 16, inStock: true, stockQuantity: 30, featured: false, prescriptionRequired: false, manufacturer: "PipettePro", sku: "PIPETTE-SET-3" },
  { id: 76, name: "CO2 Incubator 50L", description: "Water-jacketed CO2 incubator for cell and tissue culture. 50-litre capacity, humidity 95%, CO2 control 0-20%, temperature 5-50 degrees C. HEPA filter, copper interior.", price: "2800.00", originalPrice: "3500.00", imageUrl: "/products/product-76.webp", categoryId: 16, inStock: true, stockQuantity: 4, featured: false, prescriptionRequired: false, manufacturer: "LabEnviron", sku: "INCUB-CO2-50L" },
  { id: 77, name: "Medical Refrigerator 4C (300L)", description: "Pharmaceutical-grade medical refrigerator. 300-litre capacity, temperature range 2-8 degrees C. Digital display, high-temperature alarm, lockable door. Suitable for vaccines and samples.", price: "750.00", originalPrice: "950.00", imageUrl: "/products/product-77.webp", categoryId: 16, inStock: true, stockQuantity: 10, featured: true, prescriptionRequired: false, manufacturer: "MedCool", sku: "FRIDGE-MED-300" },
  { id: 78, name: "Plastic Petri Dish Box (90mm)", description: "Sterile plastic petri dishes 90mm diameter x 15mm deep. Box of 500. Clear polystyrene, gamma irradiated, individually stacked. Suitable for culture media and cell biology.", price: "35.00", originalPrice: null, imageUrl: "/products/product-78.webp", categoryId: 16, inStock: true, stockQuantity: 100, featured: false, prescriptionRequired: false, manufacturer: "LabSupply", sku: "PETRI-90-500" },
  { id: 79, name: "Spectrophotometer UV-Vis", description: "Benchtop UV-Vis spectrophotometer. Wavelength range 190-1100nm, photometric accuracy +/-0.002A. 7 inch touchscreen, built-in methods library, USB data export. Includes quartz cuvettes.", price: "1500.00", originalPrice: "2000.00", imageUrl: "/products/product-79.webp", categoryId: 16, inStock: true, stockQuantity: 6, featured: false, prescriptionRequired: false, manufacturer: "OptoLab", sku: "SPEC-UVVIS-01" },
  { id: 80, name: "Biochemical Analyzer (Semi-Auto)", description: "Semi-automated biochemistry analyzer for clinical chemistry. 340-800nm wavelength range, measures up to 50 parameters including liver, kidney, lipid panels. Printer output.", price: "1800.00", originalPrice: "2400.00", imageUrl: "/products/product-80.webp", categoryId: 16, inStock: true, stockQuantity: 7, featured: true, prescriptionRequired: false, manufacturer: "BioLab Systems", sku: "BIOCHEM-SEMI-01" },
  { id: 81, name: "Hematology Analyzer 3-Part", description: "Automated 3-part differential hematology analyzer. 60 samples/hour, 19 parameters (WBC, RBC, HGB, HCT, PLT, etc.). 10,000 sample memory, thermal printer.", price: "2200.00", originalPrice: "2900.00", imageUrl: "/products/product-81.webp", categoryId: 16, inStock: true, stockQuantity: 5, featured: true, prescriptionRequired: false, manufacturer: "HemaTech", sku: "HEMA-3PART-01" },
  { id: 82, name: "ELISA Microplate Reader", description: "Microplate ELISA reader for 96-well and 48-well plates. 8-channel filter reading, wavelength range 400-750nm, 2nm bandwidth. USB output, built-in shaker option.", price: "1600.00", originalPrice: "2100.00", imageUrl: "/products/product-82.webp", categoryId: 16, inStock: true, stockQuantity: 5, featured: false, prescriptionRequired: false, manufacturer: "BioLab Systems", sku: "ELISA-READER-01" },
  { id: 83, name: "Microcentrifuge 1.5-2ml", description: "Compact microcentrifuge for 1.5ml and 2ml Eppendorf tubes. 12-place rotor, max 14,000 RPM, digital timer. Brushless motor, quiet, compact footprint.", price: "280.00", originalPrice: "370.00", imageUrl: "/products/product-83.webp", categoryId: 16, inStock: true, stockQuantity: 20, featured: false, prescriptionRequired: false, manufacturer: "LabCentro", sku: "MICROCENTRI-01" },
  { id: 84, name: "Analytical Balance (0.0001g)", description: "Analytical precision balance. Capacity 220g, readability 0.1mg (0.0001g). Draft shield, internal calibration, RS232 output. Suitable for pharmaceutical dispensing.", price: "450.00", originalPrice: "600.00", imageUrl: "/products/product-84.webp", categoryId: 16, inStock: true, stockQuantity: 15, featured: false, prescriptionRequired: false, manufacturer: "BalancePro", sku: "BALANCE-ANA-01" },
  { id: 85, name: "Medical Freezer -20C (100L)", description: "Upright medical freezer for laboratory storage at -20 degrees C. 100-litre capacity, temperature range -10 to -25 degrees C. Alarm, lockable door, energy efficient compressor.", price: "680.00", originalPrice: "900.00", imageUrl: "/products/product-85.webp", categoryId: 16, inStock: true, stockQuantity: 8, featured: false, prescriptionRequired: false, manufacturer: "MedCool", sku: "FREEZER-20-100" },
  { id: 86, name: "Ultra-Low Freezer -80C (50L)", description: "Ultra-low temperature freezer for long-term biological sample storage at -80 degrees C. 50-litre capacity, CFC-free refrigerant, alarm system, password protection.", price: "3200.00", originalPrice: "4200.00", imageUrl: "/products/product-86.webp", categoryId: 16, inStock: true, stockQuantity: 3, featured: false, prescriptionRequired: false, manufacturer: "MedCool", sku: "FREEZER-80-50" },
  { id: 87, name: "Laminar Flow Hood (Vertical)", description: "Vertical laminar flow clean bench. Class 100 cleanliness, HEPA filter (99.99% efficiency), UV sterilization lamp, tempered glass sash. 900mm working width.", price: "1850.00", originalPrice: "2400.00", imageUrl: "/products/product-87.webp", categoryId: 16, inStock: true, stockQuantity: 4, featured: false, prescriptionRequired: false, manufacturer: "LabEnviron", sku: "LAMINAR-FLOW-01" },
  { id: 88, name: "Magnetic Stirrer with Hotplate", description: "Magnetic stirrer with integrated hotplate. Temperature up to 340 degrees C, stirring speed 100-1500 RPM. External temperature probe, ceramic coated surface, digital display.", price: "95.00", originalPrice: "130.00", imageUrl: "/products/product-88.webp", categoryId: 16, inStock: true, stockQuantity: 30, featured: false, prescriptionRequired: false, manufacturer: "LabMix", sku: "STIRRER-HOT-01" },
  { id: 89, name: "Digital X-Ray Machine (DR)", description: "Wall-mounted direct digital radiography X-Ray system. 40kW generator, 100mA, flat panel detector. DICOM 3.0 compatible, automatic exposure control, instant image preview.", price: "18500.00", originalPrice: "24000.00", imageUrl: "/products/product-89.webp", categoryId: 17, inStock: true, stockQuantity: 2, featured: true, prescriptionRequired: false, manufacturer: "RadTech", sku: "XRAY-DR-WALL-01" },
  { id: 90, name: "Portable Ultrasound Scanner", description: "Laptop-style portable color doppler ultrasound. 15 inch LED display, 3 probe ports. Supports abdominal, cardiac, obstetric, musculoskeletal modes. DICOM, USB, built-in battery.", price: "8500.00", originalPrice: "11000.00", imageUrl: "/products/product-90.webp", categoryId: 17, inStock: true, stockQuantity: 5, featured: true, prescriptionRequired: false, manufacturer: "UltraView", sku: "US-PORT-COLOR-01" },
  { id: 91, name: "Ultrasound Linear Probe (7.5MHz)", description: "High-frequency linear ultrasound probe for vascular and superficial imaging. 7.5MHz frequency, 40mm footprint. Compatible with major portable and cart ultrasound systems.", price: "850.00", originalPrice: "1100.00", imageUrl: "/products/product-91.webp", categoryId: 17, inStock: true, stockQuantity: 15, featured: false, prescriptionRequired: false, manufacturer: "UltraView", sku: "PROBE-LIN-7.5" },
  { id: 92, name: "C-Arm Fluoroscopy Machine", description: "Mobile C-arm fluoroscopy system for intraoperative imaging. 9-inch image intensifier, 15kW generator. 7 inch monitor pair, last-image hold, pulsed fluoroscopy.", price: "28000.00", originalPrice: "36000.00", imageUrl: "/products/product-92.webp", categoryId: 17, inStock: true, stockQuantity: 1, featured: false, prescriptionRequired: false, manufacturer: "RadTech", sku: "CARM-FLUORO-01" },
  { id: 93, name: "DICOM Workstation & PACS", description: "Medical-grade DICOM viewing workstation with PACS software. Dual 5MP medical monitors, GPU-accelerated 3D rendering. Supports CR/DR/CT/MRI. 10TB storage.", price: "4500.00", originalPrice: "6000.00", imageUrl: "/products/product-93.webp", categoryId: 17, inStock: true, stockQuantity: 5, featured: false, prescriptionRequired: false, manufacturer: "RadTech", sku: "PACS-WS-01" },
  { id: 94, name: "12-Lead ECG Machine", description: "Digital 12-lead ECG recording system. Automatic interpretation, thermal printer, 10,000 ECG memory. Touchscreen, WiFi/USB connectivity, rechargeable battery.", price: "680.00", originalPrice: "900.00", imageUrl: "/products/product-94.webp", categoryId: 18, inStock: true, stockQuantity: 20, featured: true, prescriptionRequired: false, manufacturer: "CardioTech", sku: "ECG-12LEAD-01" },
  { id: 95, name: "Automated External Defibrillator (AED)", description: "Semi-automatic AED for public access defibrillation. Voice guidance, visual prompts, CPR coaching. IP55 rated, 7-year battery life, self-test function.", price: "1200.00", originalPrice: "1600.00", imageUrl: "/products/product-95.webp", categoryId: 18, inStock: true, stockQuantity: 15, featured: true, prescriptionRequired: false, manufacturer: "DefibTech", sku: "AED-AUTO-01" },
  { id: 96, name: "Biphasic Defibrillator Monitor", description: "Advanced cardiac defibrillator with ECG monitor. 360J biphasic energy, AED mode, external pacing, SpO2 and NIBP monitoring. 8 inch colour display.", price: "3500.00", originalPrice: "4500.00", imageUrl: "/products/product-96.webp", categoryId: 18, inStock: true, stockQuantity: 8, featured: true, prescriptionRequired: false, manufacturer: "DefibTech", sku: "DEFIB-BIPH-01" },
  { id: 97, name: "Holter Monitor 24h (12-Lead)", description: "Ambulatory 12-lead Holter ECG recorder. 48-hour continuous recording, lightweight 65g device, USB data transfer. Analysis software included for Windows.", price: "550.00", originalPrice: "720.00", imageUrl: "/products/product-97.webp", categoryId: 18, inStock: true, stockQuantity: 12, featured: false, prescriptionRequired: false, manufacturer: "CardioTech", sku: "HOLTER-12L-01" },
  { id: 98, name: "Cardiac Stress Test System", description: "Treadmill ergometry stress test system. Includes programmable treadmill, 12-lead ECG acquisition, real-time ST analysis, and exercise protocols (Bruce, Balke, Naughton).", price: "4800.00", originalPrice: "6200.00", imageUrl: "/products/product-98.webp", categoryId: 18, inStock: true, stockQuantity: 3, featured: false, prescriptionRequired: false, manufacturer: "CardioTech", sku: "STRESS-TEST-01" },
  { id: 99, name: "Slit Lamp Biomicroscope", description: "Binocular slit lamp for anterior segment examination. 5-step magnification 6x-40x, halogen illumination, joystick control, chin rest. Photographic attachment port.", price: "1800.00", originalPrice: "2400.00", imageUrl: "/products/product-99.webp", categoryId: 19, inStock: true, stockQuantity: 5, featured: false, prescriptionRequired: false, manufacturer: "OphthalTech", sku: "SLIT-LAMP-01" },
  { id: 100, name: "Auto Refractometer / Keratometer", description: "Automated refractometer and keratometer for objective measurement of refractive error and corneal curvature. LCD touchscreen, motorized chin rest, measurement memory.", price: "2200.00", originalPrice: "2900.00", imageUrl: "/products/product-100.webp", categoryId: 19, inStock: true, stockQuantity: 4, featured: false, prescriptionRequired: false, manufacturer: "OphthalTech", sku: "AUTOREF-KERAT-01" },
  { id: 101, name: "Ophthalmoscope Direct", description: "Direct ophthalmoscope with fibre-optic illumination. 28 lens powers (+20 to -25D), 5 apertures, 6 filters. Rechargeable battery handle, suitable for fundus examination.", price: "85.00", originalPrice: "115.00", imageUrl: "/products/product-101.webp", categoryId: 19, inStock: true, stockQuantity: 30, featured: false, prescriptionRequired: false, manufacturer: "DiagnoScope", sku: "OPHTHAL-DIRECT-01" },
  { id: 102, name: "Non-Contact Tonometer", description: "Non-contact air puff tonometer for intraocular pressure measurement. Auto-measurement, 3 readings averaged, motorized chin rest. Suitable for glaucoma screening.", price: "2800.00", originalPrice: "3600.00", imageUrl: "/products/product-102.webp", categoryId: 19, inStock: true, stockQuantity: 3, featured: false, prescriptionRequired: false, manufacturer: "OphthalTech", sku: "TONOMETER-NCT-01" },
  { id: 103, name: "Visual Acuity Chart (LED)", description: "LED-backlit visual acuity projection chart. Distance 3m and 6m testing, remote control, multiple optotype formats (Snellen, LogMAR, children). Wall-mounted.", price: "250.00", originalPrice: "320.00", imageUrl: "/products/product-103.webp", categoryId: 19, inStock: true, stockQuantity: 20, featured: false, prescriptionRequired: false, manufacturer: "OphthalTech", sku: "VA-CHART-LED-01" },
  { id: 104, name: "Portable Oxygen Concentrator 5L", description: "Portable oxygen concentrator. 5L/min flow, 93% purity, low noise <45dB. LED alarm panel, AC+DC power, carry handle with wheels. 24/7 continuous use rated.", price: "650.00", originalPrice: "850.00", imageUrl: "/products/product-104.webp", categoryId: 20, inStock: true, stockQuantity: 25, featured: true, prescriptionRequired: false, manufacturer: "OxyGen Pro", sku: "OXY-CONC-5L-01" },
  { id: 105, name: "High-Flow Oxygen System", description: "High-flow nasal cannula (HFNC) oxygen therapy system. Flow up to 60L/min, temperature 31-37 degrees C, humidity 100%. For adult and pediatric use in acute respiratory care.", price: "2800.00", originalPrice: "3700.00", imageUrl: "/products/product-105.webp", categoryId: 20, inStock: true, stockQuantity: 6, featured: true, prescriptionRequired: true, manufacturer: "RespiCare", sku: "HFNC-SYSTEM-01" },
  { id: 106, name: "CPAP / BiPAP Machine", description: "Bilevel positive airway pressure machine for sleep apnea and respiratory support. Pressure 4-25cmH2O, built-in humidifier, compliance data recording, auto-adjusting mode.", price: "450.00", originalPrice: "600.00", imageUrl: "/products/product-106.webp", categoryId: 20, inStock: true, stockQuantity: 20, featured: true, prescriptionRequired: false, manufacturer: "RespiCare", sku: "CPAP-BIPAP-01" },
  { id: 107, name: "Jet Nebulizer Compressor", description: "Jet compressor nebulizer for aerosol medication delivery. MMAD <5μm, 0.3ml/min output. Includes adult and child masks, mouthpiece, 2m tubing. Quiet <60dB.", price: "32.00", originalPrice: "45.00", imageUrl: "/products/product-107.webp", categoryId: 20, inStock: true, stockQuantity: 100, featured: false, prescriptionRequired: false, manufacturer: "RespiCare", sku: "NEB-JET-01" },
  { id: 108, name: "Peak Flow Meter", description: "Mini-Wright peak flow meter for monitoring asthma and COPD. Range 60-800 L/min, includes standard and low-range scale. Disposable mouthpieces pack of 5 included.", price: "18.00", originalPrice: null, imageUrl: "/products/product-108.webp", categoryId: 20, inStock: true, stockQuantity: 150, featured: false, prescriptionRequired: false, manufacturer: "RespiCare", sku: "PEAK-FLOW-01" },
  { id: 109, name: "Bedside Patient Monitor (5-param)", description: "Bedside 5-parameter patient monitor. ECG, SpO2, NIBP, temperature, respiration. 10.4 inch colour touchscreen, alarm system, 72h trend storage, nurse call interface.", price: "950.00", originalPrice: "1250.00", imageUrl: "/products/product-109.webp", categoryId: 21, inStock: true, stockQuantity: 20, featured: true, prescriptionRequired: false, manufacturer: "VitalMonitor", sku: "MON-BED-5P-01" },
  { id: 110, name: "Central Monitoring Station", description: "Central nurse station monitoring system. Displays up to 16 bedside monitors simultaneously on 27 inch LCD. Real-time alarms, historical data, bed labeling.", price: "3200.00", originalPrice: "4200.00", imageUrl: "/products/product-110.webp", categoryId: 21, inStock: true, stockQuantity: 3, featured: false, prescriptionRequired: false, manufacturer: "VitalMonitor", sku: "MON-CENTRAL-01" },
  { id: 111, name: "Transport Patient Monitor", description: "Compact transport monitor for ICU and emergency transfer. ECG, SpO2, NIBP, temperature. Shock-proof, IP44, 6-hour battery. Includes mounting bracket.", price: "1100.00", originalPrice: "1450.00", imageUrl: "/products/product-111.webp", categoryId: 21, inStock: true, stockQuantity: 10, featured: false, prescriptionRequired: false, manufacturer: "VitalMonitor", sku: "MON-TRANSPORT-01" },
  { id: 112, name: "Infusion Pump (Volumetric)", description: "Volumetric infusion pump. Rate 0.1-999.9 ml/h, volume to be infused 0-9999ml. Air bubble, occlusion, and empty bag alarms. Battery backup 6 hours, pole clamp included.", price: "680.00", originalPrice: "900.00", imageUrl: "/products/product-112.webp", categoryId: 21, inStock: true, stockQuantity: 25, featured: true, prescriptionRequired: false, manufacturer: "InfuTech", sku: "INF-PUMP-VOL-01" },
  { id: 113, name: "Syringe Infusion Pump", description: "Single-channel syringe infusion pump. Compatible with 10-50ml syringes, rate 0.001-1200 ml/h. Accurate bolus function, drug library, keep-vein-open mode. 8h battery.", price: "420.00", originalPrice: "580.00", imageUrl: "/products/product-113.webp", categoryId: 21, inStock: true, stockQuantity: 30, featured: true, prescriptionRequired: false, manufacturer: "InfuTech", sku: "SYR-PUMP-01" },
  { id: 114, name: "Large Autoclave Steam Sterilizer (80L)", description: "Horizontal floor-standing autoclave. 80-litre chamber, vacuum system, 134 degrees C cycle. Automatic door lock, printout recorder, CSSD use. Stainless steel interior.", price: "4200.00", originalPrice: "5500.00", imageUrl: "/products/product-114.webp", categoryId: 22, inStock: true, stockQuantity: 4, featured: false, prescriptionRequired: false, manufacturer: "SterilTech", sku: "AUTO-80L-FLOOR" },
  { id: 115, name: "Ultrasonic Cleaner (Dental/Surgical)", description: "Ultrasonic instrument cleaner. 6-litre tank, 40kHz frequency, digital timer and temperature control. Stainless steel tank and lid. For pre-cleaning instruments before sterilization.", price: "185.00", originalPrice: "250.00", imageUrl: "/products/product-115.webp", categoryId: 22, inStock: true, stockQuantity: 20, featured: false, prescriptionRequired: false, manufacturer: "SterilTech", sku: "ULTRA-CLEAN-6L" },
  { id: 116, name: "UV Sterilization Cabinet", description: "UV-C sterilization cabinet for small instruments and mobile devices. 2 UV lamps, ozone disinfection, timer. Stainless steel interior, 30L capacity. Desktop model.", price: "95.00", originalPrice: "130.00", imageUrl: "/products/product-116.webp", categoryId: 22, inStock: true, stockQuantity: 35, featured: false, prescriptionRequired: false, manufacturer: "SterilTech", sku: "UV-CABINET-30L" },
  { id: 117, name: "Disinfectant Fogging Machine", description: "Electric disinfectant fogging machine for room sterilization. 1500W motor, 15L tank, coverage up to 500m2 per tank. Adjustable nozzle, shoulder strap for mobility.", price: "150.00", originalPrice: "200.00", imageUrl: "/products/product-117.webp", categoryId: 22, inStock: true, stockQuantity: 25, featured: false, prescriptionRequired: false, manufacturer: "SterilTech", sku: "FOGGER-ROOM-01" },
  { id: 118, name: "Hospital Bed (Manual)", description: "Manual 3-function hospital bed. Head, knee, and height adjustment via crank. Fowler position, ABS side rails, 4 castors with brakes. Weight capacity 200kg.", price: "650.00", originalPrice: "850.00", imageUrl: "/products/product-118.webp", categoryId: 23, inStock: true, stockQuantity: 20, featured: true, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "BED-HOSP-MAN-01" },
  { id: 119, name: "Electric ICU Hospital Bed", description: "Electric 4-function ICU hospital bed. Full fowler, knee, head, height adjustments via hand control. Integrated weighing scale, cardiac chair position, 4 full-length side rails.", price: "2800.00", originalPrice: "3600.00", imageUrl: "/products/product-119.webp", categoryId: 23, inStock: true, stockQuantity: 8, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "BED-ICU-ELEC-01" },
  { id: 120, name: "Medical Overbed Table", description: "Height adjustable overbed table with tilting tabletop. Range 65-105cm, castors with brakes. Laminate surface, stainless steel frame. Load capacity 15kg.", price: "85.00", originalPrice: "115.00", imageUrl: "/products/product-120.webp", categoryId: 23, inStock: true, stockQuantity: 50, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "OVERBED-TABLE-01" },
  { id: 121, name: "IV Pole / Drip Stand", description: "Stainless steel 5-hook IV pole with weighted base and 5 castors. Height adjustable 135-200cm. Holds up to 4 infusion bags simultaneously. Rust-resistant.", price: "35.00", originalPrice: null, imageUrl: "/products/product-121.webp", categoryId: 23, inStock: true, stockQuantity: 80, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "IV-POLE-5HOOK" },
  { id: 122, name: "Medical Instrument Trolley", description: "Stainless steel medical trolley with 2 shelves and push handle. 60x40x90cm, 4 swivel castors with brakes. Load capacity 50kg per shelf. Easy-clean surface.", price: "120.00", originalPrice: "160.00", imageUrl: "/products/product-122.webp", categoryId: 23, inStock: true, stockQuantity: 40, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "TROLLEY-INSTR-01" },
  { id: 123, name: "Bedside Cabinet / Locker", description: "Hospital bedside cabinet with lockable upper cupboard and lower open shelf. Smooth castors, ABS construction, easy-wipe surface. Storage for personal items.", price: "68.00", originalPrice: "90.00", imageUrl: "/products/product-123.webp", categoryId: 23, inStock: true, stockQuantity: 60, featured: false, prescriptionRequired: false, manufacturer: "MedFurniture", sku: "BEDSIDE-CAB-01" },
  { id: 124, name: "Trauma First Response Bag", description: "Large professional trauma bag with dedicated compartments. Includes tourniquet, hemostatic dressing, chest seals (vented + non-vented), decompression needle, trauma shears, gloves.", price: "95.00", originalPrice: "130.00", imageUrl: "/products/product-124.webp", categoryId: 24, inStock: true, stockQuantity: 50, featured: true, prescriptionRequired: false, manufacturer: "EmergencyMed", sku: "TRAUMA-BAG-01" },
  { id: 125, name: "Spine Board & Head Immobilizer", description: "Radiolucent long spine board with 9 body-straps. Head immobilizer set with 2 side blocks and chin strap. X-ray compatible, buoyant, handles on sides and ends.", price: "145.00", originalPrice: "195.00", imageUrl: "/products/product-125.webp", categoryId: 24, inStock: true, stockQuantity: 25, featured: false, prescriptionRequired: false, manufacturer: "EmergencyMed", sku: "SPINE-BOARD-01" },
  { id: 126, name: "Scoop Stretcher (Aluminium)", description: "Aluminium scoop stretcher for patient extraction from confined spaces. Adjustable length 168-200cm, weight capacity 150kg. Quick-release latches, radiolucent.", price: "95.00", originalPrice: "125.00", imageUrl: "/products/product-126.webp", categoryId: 24, inStock: true, stockQuantity: 20, featured: false, prescriptionRequired: false, manufacturer: "EmergencyMed", sku: "SCOOP-STRETCH-01" },
  { id: 127, name: "Bag Valve Mask (BVM) Set", description: "Adult, child, and infant BVM resuscitator set. 1600ml, 500ml, and 240ml bags. Non-rebreather valve, reservoir bag, transparent masks sizes 0-5. PEEP valve included.", price: "45.00", originalPrice: null, imageUrl: "/products/product-127.webp", categoryId: 24, inStock: true, stockQuantity: 80, featured: false, prescriptionRequired: false, manufacturer: "RespiCare", sku: "BVM-SET-3" },
  { id: 128, name: "Tourniquet CAT Combat Application", description: "Combat application tourniquet (CAT) for extremity haemorrhage control. Single-handed application, windlass tightening, time of application tab. Black and orange available.", price: "22.00", originalPrice: null, imageUrl: "/products/product-128.webp", categoryId: 24, inStock: true, stockQuantity: 200, featured: true, prescriptionRequired: false, manufacturer: "EmergencyMed", sku: "TOURNI-CAT-01" },
];

export async function seedIfEmpty(logger: Logger): Promise<void> {
  try {
    const result = await db.execute<{ count: number }>(sql`SELECT COUNT(*)::int as count FROM products`);
    const count = result.rows[0]?.count ?? 0;
    if (Number(count) > 0) {
      logger.info("Database already seeded, skipping.");
      return;
    }

    logger.info("Empty database detected — seeding categories and products...");

    // Reset sequences first
    await db.execute(sql`ALTER SEQUENCE categories_id_seq RESTART WITH 1`);
    await db.execute(sql`ALTER SEQUENCE products_id_seq RESTART WITH 1`);

    // Insert categories
    for (const cat of categories) {
      await db.execute(
        sql`INSERT INTO categories (id, name, slug, description, image_url) VALUES (${cat.id}, ${cat.name}, ${cat.slug}, ${cat.description}, ${cat.imageUrl})`
      );
    }
    // Fix sequence after explicit IDs
    await db.execute(sql`SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories))`);

    // Insert products in batches of 20
    const batchSize = 20;
    for (let i = 0; i < products.length; i += batchSize) {
      const batch = products.slice(i, i + batchSize);
      for (const p of batch) {
        await db.execute(
          sql`INSERT INTO products (id, name, description, price, original_price, image_url, category_id, in_stock, stock_quantity, featured, prescription_required, manufacturer, sku)
              VALUES (${p.id}, ${p.name}, ${p.description}, ${p.price}::numeric, ${p.originalPrice}::numeric, ${p.imageUrl}, ${p.categoryId}, ${p.inStock}, ${p.stockQuantity}, ${p.featured}, ${p.prescriptionRequired}, ${p.manufacturer}, ${p.sku})`
        );
      }
    }
    // Fix sequence after explicit IDs
    await db.execute(sql`SELECT setval('products_id_seq', (SELECT MAX(id) FROM products))`);

    logger.info(`Seeded ${categories.length} categories and ${products.length} products successfully.`);
  } catch (err) {
    logger.error({ err }, "Seed failed");
  }
}
